### ISSUE TITLE
Any requirements to run this Slurm container?

### ISSUE THREAD

**Issue by marcodelapierre** [PawseySC/pawsey-containers#13]
https://github.com/PawseySC/pawsey-containers/blob/82c412e878793b804e1e178b2c8a0e2b4935ce0a/slurm/slurm-base/buildslurm.dockerfile#L103

@pelahi can you comment on which bind mounts and/or Singularity configs and/or host configs required for this container to work. Also, what is the scope: Setonix-only, or any machine? Thank you

**Comment by pelahi** [comment]
The main commands that need to be run are 
```
-B /var/run/munge/munge.socket.2,/etc/slurm
```
for a non-configless slurm deployment. I mount `munge` to ensure authentication. The configuration for slurm is in `/etc/slurm`. 

Note that the versions of within the container likely have to be VERY close to that running on the host for this work. Currently I have tried where the differences are at the patch level and there are warnings so there could be unforeseen behaviour. Larger differences can result in errors if using plugins.

**Comment by marcodelapierre** [comment]
Thanks Pascal!

Would this image be able to run standalone, e.g. on a VM, and act as a Slurm simulator?
Or is it only supposed to be a base image to build containers for Setonix?

Only in the former case, it would be very good to contribute a corresponding SHPC manifest here: https://github.com/singularityhub/shpc-registry/tree/main/quay.io/pawsey
